#!/bin/bash

echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"

# clean up
rm -rf public; mkdir -p public

# Build the project.
hugo # if using a theme, replace by `hugo -t <yourtheme>`

# Go To Public folder
cd public
git init
# Add changes to git.
git add -A

# Commit changes.
msg="rebuilding site `date`"
if [ $# -eq 1 ]
  then msg="$1"
fi
git remote add origin git@github.com:vigneshsarma/vigneshsarma.github.com.git
git commit -m "$msg"

# Push source and build repos.
git push -f origin master

# Come Back
cd ..
